### ISSUE TITLE
Add support for aws cli and s3 history option

### ISSUE THREAD

**Issue by istrau3** [satoshipay/docker-stellar-core#1]
Basically, allow a user to specify an s3 history option similar to this:
https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_example.cfg#L314

**Comment by istrau3** [comment]
@andrenarchy I have done a bunch of work on this issue (as well as some other things) in my fork(s). Will you be on the stellar slack so we can discuss (before I create a PR)?

**Comment by andrenarchy** [comment]
Closed, see #2
