### ISSUE TITLE
Add instructions to run `entry.sh` before `stellar-core --conf...`?

### ISSUE THREAD

**Issue by ramontayag** [satoshipay/docker-stellar-core#13]
My setup might be different, but I was having sync issues until I ran `stellar-core --conf /stellar-core.cfg --newdb`. I see that this repo has the command in `entry.sh` (except it's not double-hyphen -- not sure if it makes a difference), and seems if I had run `entry.sh` before `stellar-core --conf /stellar-core.cfg --newdb`, I would not have seen those sync issues.

I don't mind adding the instructions, but wanted to bring it up because maybe it's my setup that's weird or there's a dockerism I'm not following.

**Comment by andrenarchy** [comment]
`entry.sh` should always be run before the actual Stellar Core command is executed. This is what the `ENTRYPOINT` directive here does:

https://github.com/satoshipay/docker-stellar-core/blob/b0f69f6c010d178f95f247ec210bb39eeb7a1715/Dockerfile#L33

Maybe you have been overriding the entrypoint? I'm closing this now but feel free to re-open if you still experience problems.

**Comment by ramontayag** [comment]
No, I haven't seen this in a while. I don't recall what that setup was like. 👍
